#ifndef UAC_H
#define UAC_H

#define UAC_INTERFACE_ASSOCIATION_DESCRIPTOR_TYPE	0x0B

#define UAC_SUBCLASS_AUDIOCONTROL			0x01
#define UAC_SUBCLASS_AUDIOSTREAMING			0x02

#define UAC_CS_INTERFACE				0x24
#define UAC_CS_ENDPOINT					0x25

#define UAC_AC_HEADER					0x01
#define UAC_AC_INPUT_TERMINAL				0x02
#define UAC_AC_OUTPUT_TERMINAL				0x03

#define UAC_AS_GENERAL					0x01
#define UAC_AS_FORMAT_TYPE				0x02
#define UAC_FORMAT_TYPE_I				0x01
#define UAC_FORMAT_PCM					0x0001

#define UAC_TERMINAL_USB_STREAMING			0x0101
#define UAC_TERMINAL_LINE_CONNECTOR			0x0603

#define UAC_ENDPOINT_GENERAL				0x01
#define UAC_ENDPOINT_ASYNC_ISOCHRONOUS_IN		0x05

#define UAC_SAMPLE_RATE					48000
#define UAC_CHANNEL_COUNT				2
#define UAC_BYTES_PER_SAMPLE				2
#define UAC_NOMINAL_PACKET_FRAMES			48
#define UAC_MAX_PACKET_FRAMES				49
#define UAC_MAX_PACKET_SIZE				\
	(UAC_MAX_PACKET_FRAMES * UAC_CHANNEL_COUNT * UAC_BYTES_PER_SAMPLE)

#endif
